config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
    
  resources :spells
  resources :books
  resources :spellclasses
  
  post 'books/:id', to: 'books#delete_spell', as: 'delete_spell'
  post 'books/:id/add_spell_book', to: 'books#add_spell_book', as: 'add_spell_book'
  get 'spells/:id/add_spell', to: 'spells#add', as: 'add' 
  post 'spells/:id/add_spell_in_book', to: 'spells#add_spell', as: 'add_spell_in_book'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :spells
 
  validates_presence_of :name
  validates_length_of :name, maximum: 70
  
  validates :name, uniqueness: true
  validates_uniqueness_of :name, :case_sensitive => false
  

  

  def spell_count
      spells.select('name').count
  end
  

  def spell_display
      arr = []
      arr = spells      
      return arr
  end
  
  def all_spells
      arr = []   
      arr = Spell.all
      return arr.length
  end

    
end

app/models/spell.rb
class Spell < ApplicationRecord
  has_and_belongs_to_many :books
  has_and_belongs_to_many :spellclasses
  
  validates_presence_of :name
  validates_length_of :name, maximum: 70
  validates :name, uniqueness: true
  validates_presence_of :level
  validates_numericality_of :level, only_integer: true, greater_than: -1, less_than: 10  
  validates_presence_of :school
  validates :concentration, inclusion: [true, false]
  validates_uniqueness_of :name, :case_sensitive => false
  

    
    def class_dis
       arr = []
       arr = spellclasses
        return arr
    end
    
    def con_dis
        if concentration
            return "Yes"
        else 
            return "No"
        end
    end
    
end

app/models/spellclass.rb
class Spellclass < ApplicationRecord
  has_and_belongs_to_many :spells
  
  validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
 class BooksController < ApplicationController
  def index
      @books = Book.all
  end

  def create
      @book = Book.new(book_params)
      
      if @book.save
          flash[:notice] = "Successfully added #{@book.name} to All book"
          redirect_to books_url
      else
#           flash[:notice] = 'unable to add book'
          render :new
      end
  end

  def new
      @book = Book.new
  end

  def edit
      @book = Book.find(params[:id])
  end

  def show
      @book = Book.find(params[:id])
  end

  def update
      @book = Book.find(params[:id])  
      if @book.update(book_params)
          flash[:notice] = "#{@book.name} was successfully updated " 
          redirect_to @book
      else
          render :edit
      end
  end

  def destroy
    @book = Book.find(params[:id])  
        if @book.destroy
            flash[:notice] = "#{@book.name} was successfully deleted."
        else
            flash[:notice] = "Unable to delete #{@book.name}."
        end
      
        redirect_to books_url 
  end
  
  def delete_spell
      @book = Book.find(params[:id])
      @spell = Spell.find(params[:spell])
      
      if @book = @book.spells.delete(@spell)
          flash[:notice] = "#{@spell.name} successfully removed"
      else
          flash[:notice] = "unable to remove #{@spell.name}"
      end
      redirect_to book_url
  end  
    
  def add_spell_book
      @book = Book.find(params[:id])
      @spell = Spell.find(params[:spell_id])
      
      if !@book.spells.include?(@spell)
         @book.spells << @spell
         flash[:notice] = "#{@spell.name} was added successfully to #{@book.name}"
      else 
         flash[:notice] = "Unable to add #{@spell.name} to #{@book.name}"
      end
      
      redirect_to book_url
  end 
    
  private
    # Only allow a trusted parameter "white list" through.
    def book_params
      # params is a hashtable.  It should have in it a key of :book.
      # The value for the :book key is another hash.
      # If params does not contain the key :book, an exception is raised.  
      # Only the "book" hash is returned and only with the permitted key(s).
      # So returns a hash with only having at most keys of :title, :year, :author_id
      params.require(:book).permit(:name)
    end
    
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  def index
      @spells = Spell.all
  end

  def create
      @spell = Spell.new(spell_params)
      
      if @spell.save
          flash[:notice] = "Successfully added #{@spell.name} to All Spells"
          redirect_to spells_url
      else
          render :new
      end
  end

  def new
      @spell = Spell.new
  end

  def edit
      @spell = Spell.find(params[:id])
  end

  def show
      @spell = Spell.find(params[:id])
  end

  def update
      @spell = Spell.find(params[:id])  
      if @spell.update(spell_params)
          flash[:notice] = "Successfully updated #{@spell.name}" 
          redirect_to spells_url
      else
          render :edit
      end
      
  end

  def destroy
      @spell = Spell.find(params[:id])  
          if @spell.destroy 
              flash[:notice] = "Successfully deleted #{@spell.name}"
          else
              flash[:notice] = 'Unable to delete spell.'
          end
      
      redirect_to spells_url
  end
  
  def add  
      @spell = Spell.find(params[:id])
  end 
   
  def add_spell
      @spell = Spell.find(params[:id])
      @book = Book.find(params[:book_ids])
      
      if !@book.spells.include?(@spell)
          @spell.books << @book
          flash[:notice] = "Successfully added #{@spell.name} to #{@book.name}"
      else 
          flash[:notice] = 'Unable to add'
      end
      redirect_to spells_url    
  end
    
    private
    # Only allow a trusted parameter "white list" through.
    def spell_params
      # params is a hashtable.  It should have in it a key of :book.
      # The value for the :book key is another hash.
      # If params does not contain the key :book, an exception is raised.  
      # Only the "book" hash is returned and only with the permitted key(s).
      # So returns a hash with only having at most keys of :title, :year, :author_id
      params.require(:spell).permit(:name, :level, :school, :concentration, :description, spellclass_ids: [])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<p id="notice"><%= flash[:notice] %></p>
<h1>
    <strong>Add Spell to </strong>
    <%= @book.name %>
</h1>

<p>
    <%= link_to "Back to #{@book.name}", book_path %>
    <%= link_to "Home", root_path %> 
</p>

<table>
    <thead>
      <tr>
          <th>Level</th>
          <th>Spellname</th>
          <th>School</th>
          <th>Classes</th>
          <th>Concentration</th>
          <th colspan="5"></th>
      </tr>
    </thead>
    
      <tbody>
          <% Spell.all.each do |s| %>
              <tr>
                  <td><%= s.level %></td>
                  <td><%= link_to s.name, spell_path %></td>
                  <td><%= s.school %></td>
                  <td>
                      <% a = [] %>
                      <% s.class_dis.each do |i| %>
                      <% a << i.name %>
                      <% end %>
                      <%= a.join(', ') %>    
                  </td>      
                  <td><%= s.con_dis %></td>
                  <td><% if @book.spells.include?(s) %>
                      Already in book
                      <% else %>
                      <%= form_with(url: add_spell_book_path(@book), local: true) do |v| %>
                      <%= hidden_field_tag 'spell_id', s.id %>
                      <%= v.submit 'Add to Book' %>
                      <% end %>  
                  <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
    

app/views/books/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>All Books</h1>

<p>
<%= link_to 'Create Book', new_book_path %> |
<%= link_to "Home", root_path %>    
</p>

<table>
  <thead>
      <tr>
          <th><%=  'Spell Count' %></th>
          <th><%=  'Name' %></th>
          <th colspan="2"></th>
      </tr>
  </thead>
  
  <tbody>
    <% @books.each do |book| %> 
      <tr>
        <td><%= book.spell_count %></td>
        <td><%= link_to book.name, book %></td>
        <td><%= form_with model: book, method: :delete, local: true do |del| %>
            <%= del.submit 'Delete Book' %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/books/new.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>New Book</h1>

<%= render 'form', book: @book %>

<p>
    <%= link_to 'Show Books', books_path %> |
    <%= link_to 'Home', root_path %>
</p>

app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>
<h1>
  <Strong>Title:</Strong>
  <%= @book.name %>
</h1>

<p>
<%= link_to 'All Books', books_path %> |
<%= link_to "Home", root_path %> 
</p>
<table>
     <thead>
      <tr>
          <th>Level</th>
          <th>Spellname</th>
          <th>School</th>
          <th>Classes</th>
          <th>Concentration</th>
          <th colspan="5"></th>
      </tr>
    </thead>
      <tbody>
          <% @book.spell_display.each do |dis| %>
              <tr>
                  <td><%= dis.level %></td>
                  <td><%= dis.name %></td>  
                  <td><%= dis.school %></td>
                  <td>
                      <% s = [] %>
                      <% dis.class_dis.each do |v|%>
                      <% s << v.name %>
                      <% end %>
                      <%= s.join(', ') %>
                  </td>
                  <td><%= dis.con_dis %></td>
                  <td><%= form_with(url: delete_spell_path(@book), local: true) do |del| %><td>
                      <%= hidden_field_tag 'spell', dis.id %>
                      <%= del.submit 'Remove Spell' %>
                      <% end %>
                  </td>
              </tr>
          <% end %>
      </tbody>
  </table>



<p>
<%= link_to 'Add Spell', edit_book_path(@book) %>
</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spellmanager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spells/_form.html.erb
<%= form_with(model: spell, local: true) do |form| %>
  <% if spell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spell.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% spell.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :level %>
    <%= form.select :level, [0,1,2,3,4,5,6,7,8,9] %>
  </div>
    
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :school %>
    <%= form.select :school, ['Conjuration', 'Necromancy', 'Evocation', 'Abjuration', 'Transmutation', 'Divination', 'Enchantment', 'Illusion'], prompt: 'Select a School'%>
  </div>

  <div class="field">
      <%= form.label :spellclass_ids, "Classes" %>
      <%= form.collection_check_boxes(:spellclass_ids, Spellclass.all, :id, :name, include_hidden: false ) %>
  </div>
  
  <div class="field">
        <%= form.label :concentration, "Yes", :value => "true" %>
        <%= form.radio_button :concentration, true%>
        <%= form.label :concentration, "No", :value => "false" %>
        <%= form.radio_button :concentration, false, :checked => true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit' %>
  </div>
<% end %>

app/views/spells/add.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>
  <strong>View</strong>
  <%= @spell.name %>
</h1>


<table>
    <p>Select Book: </p>
    <tbody>
        <tr>
        
        <td><%= form_with(url: add_spell_in_book_path(@spell), local: true) do |v| %></td>
              <%= v.collection_select(:book_ids, Book.all, :id, :name, include_hidden: false )  %>
              <%= v.submit 'Submit' %>
        <% end %>
        </tr>
    </tbody>
</table>

app/views/spells/create.html.erb
<h1>Spells#create</h1>
<p>Find me in app/views/spells/create.html.erb</p>

app/views/spells/destroy.html.erb
<h1>Spells#destroy</h1>
<p>Find me in app/views/spells/destroy.html.erb</p>

app/views/spells/edit.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>
  <strong>View</strong>
  <%= @spell.name %>
</h1>

<p>
<%= link_to 'All Spells', spells_path %> |
<%= link_to 'Home', root_path %> 
</p>

<%= render 'form', spell: @spell %>


<%= form_with model: @spell, method: :delete, local: true do |del| %><td>
    <%= del.submit 'Delete Spell' %>
    <% end %>

app/views/spells/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>All Spells</h1>
<p>
<%= link_to 'Create New', new_spell_path %> |
<%= link_to "Home", root_path %>
</p>

   


<table>
    <thead>
      <tr>
          <th>Level</th>
          <th>Spellname</th>
          <th>School</th>
          <th>Classes</th>
          <th>Concentration</th>
          <th colspan="5"></th>
      </tr>
    </thead>
    <tbody>
        <% @spells.each do |spell| %>
            <tr>
                <td><%= spell.level %></td>
                <td><%= link_to spell.name, spell %></td>
                <td><%= spell.school %></td>
                <td>
                <% s = [] %>
                <% spell.class_dis.each do |i| %>
                    <% s << i.name %>
                <% end %>
                <%= s.join(', ') %>    
                </td>      
                <td><%= spell.con_dis %></td>
                <td><%= link_to 'Edit', edit_spell_path(spell) %></td>
                <td><%= link_to "Add to Book", add_path(spell) %></td>
            </tr>
        <% end %>
  </tbody>
</table>

app/views/spells/new.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>Create New</h1>

<%= render 'form', spell: @spell %>

<p>
    <%= link_to 'All Spells', spells_path %> |
    <%= link_to 'Home', root_path %>
</p>

app/views/spells/show.html.erb
<p id="notice"><%= flash[:notice] %></p>
<h1>
  <strong>View</strong>
  <%= @spell.name %>
</h1>


<p>
<%= link_to 'All Spells', spells_path %> |
<%= link_to "Home", root_path %> 
</p>

<p>
    <strong>Level: </strong>
    <%= @spell.level %>
</p>

<p>
    <strong>Name: </strong>
    <%= @spell.name %>
</p>
    
<p>
    <strong>Name: </strong>
    <%= @spell.school %>
</p>

<p>
    <strong>Concentration: </strong>
    <%= @spell.con_dis %>
</p>

<p>
    <strong>Description: </strong>
    <%= @spell.description %>
</p>

<p>
    <%= link_to "Add #{@spell.name} to Book", add_path %>
</p>

app/views/spells/update.html.erb
<h1>Spells#update</h1>
<p>Find me in app/views/spells/update.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Home</h1>
<p><%= link_to "All Spells", spells_path %></p>
<p><%= link_to "All SpellBooks", books_path %></p> 